version: "3.2"

services:
  web:
    build:
      context: .
      dockerfile: "Dockerfile-nginx"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/usr/src/app/public
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: "Dockerfile-ruby-dev"
    command: bundle exec rails s -p 3000 -b "0.0.0.0"
    volumes:
      - bundle-data:/usr/local/bundle:cached
      - .:/usr/src/app:cached # 通常マウント
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    tty: true
    stdin_open: true

  db:
    image: postgres:latest
    volumes:
      - "db-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

volumes:
  db-data:
  bundle-data:
