default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  user: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_api_app_base_development

test:
  <<: *default
  database: rails_api_app_base_test

production:
  url: <%= ENV['DATABASE_URL'] %>
